const SUPABASE_URL = "https://fijrvolgjknanhrlikmq.supabase.co";
const SUPABASE_KEY = "sb_publishable_rDtElEk84q5UOhWqolqsdg_9_ZVkQ3m";
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
db.auth.getSession().then(({ error }) => {
  if (error) {
    console.error("Supabase connection error:", error);
  } else {
    console.log("SUPABASE CONNECTED SUCCESSFULLY");
  }
});
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const today=()=>new Date().toDateString();
const state={coins:Number(localStorage.getItem('tpa_v2_coins')||25000),boot:100,currentBet:100,pot:0,roundActive:false,seen:false,myCards:[],deck:[],round:1,room:'Rookie Club',bonusClaimed:localStorage.getItem('tpa_v2_bonus')===today(),bots:[
{id:'bot1',name:'Riya',coins:10000,folded:false,cards:[]},{id:'bot2',name:'Aman',coins:10000,folded:false,cards:[]},{id:'bot3',name:'Kabir',coins:10000,folded:false,cards:[]},{id:'bot4',name:'Meera',coins:10000,folded:false,cards:[]} ]};
const suits=[{s:'♠',red:false},{s:'♥',red:true},{s:'♦',red:true},{s:'♣',red:false}], ranks=[...Array(9)].map((_,i)=>({r:String(i+2),v:i+2})).concat([{r:'J',v:11},{r:'Q',v:12},{r:'K',v:13},{r:'A',v:14}]);
function save(){localStorage.setItem('tpa_v2_coins',state.coins);updateMoney()}function updateMoney(){['#coinBalance','#tableBalance','#myTableCoins'].forEach(id=>$(id).textContent=state.coins.toLocaleString())}
function msg(t){$('#gameLog').innerHTML='<span>♦</span> '+t}function screen(n){$('#homeScreen').classList.toggle('active',n==='home');$('#tableScreen').classList.toggle('active',n==='table');$('#bottomNav').style.display=n==='home'?'grid':'none'}
function deck(){let d=[];suits.forEach(s=>ranks.forEach(r=>d.push({...s,...r})));for(let i=d.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function card(c){return `<div class="playing-card ${c.red?'red':''}"><div class="card-rank">${c.r}</div><div class="card-suit">${c.s}</div></div>`}function showMine(){$('#myCards').innerHTML=state.myCards.map(card).join('')}function hideMine(){$('#myCards').innerHTML='<div class="playing-card back"></div><div class="playing-card back"></div><div class="playing-card back"></div>'}
function updatePot(){$('#potValue').textContent=state.pot.toLocaleString();$('#chaalAmount').textContent=state.currentBet.toLocaleString()}
function score(cs){let v=cs.map(c=>c.v).sort((a,b)=>b-a),same=cs.every(c=>c.s===cs[0].s),u=[...new Set(v)],straight=u.length===3&&(v[0]-v[2]===2||v.join(',')==='14,3,2'),high=v.join(',')==='14,3,2'?3:v[0],ct={};v.forEach(x=>ct[x]=(ct[x]||0)+1);let g=Object.entries(ct).sort((a,b)=>b[1]-a[1]||b[0]-a[0]);if(g[0][1]===3)return[6,+g[0][0]];if(straight&&same)return[5,high];if(straight)return[4,high];if(same)return[3,...v];if(g[0][1]===2)return[2,+g[0][0],+g[1][0]];return[1,...v]}
function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){let x=a[i]||0,y=b[i]||0;if(x!==y)return x-y}return 0}function handName(cs){return({6:'Trail',5:'Pure Sequence',4:'Sequence',3:'Color',2:'Pair',1:'High Card'})[score(cs)[0]]}
function resetBots(){state.bots.forEach(b=>{b.folded=false;let e=$('#'+b.id);e.querySelector('[data-status]').textContent='PLAYING';e.querySelector('.mini-cards').className='mini-cards';e.querySelector('.mini-cards').innerHTML='<i></i><i></i><i></i>'})}
function userPay(a){if(state.coins<a)return false;state.coins-=a;state.pot+=a;save();updatePot();return true}function botPay(b,a){let paid=Math.min(a,b.coins);b.coins-=paid;state.pot+=paid;$('#'+b.id).querySelector('[data-coins]').textContent=b.coins.toLocaleString();updatePot()}
function botTurn(b){if(b.folded)return;let strength=score(b.cards)[0],fold=strength<=1?.25:strength===2?.1:.02;if(Math.random()<fold){b.folded=true;$('#'+b.id).querySelector('[data-status]').textContent='PACK'}else{botPay(b,state.currentBet);$('#'+b.id).querySelector('[data-status]').textContent='CHAAL'}}
function enterRoom(boot,name){state.boot=+boot;state.currentBet=+boot;state.room=name;$('#roomTitle').textContent=name;$('#bootValue').textContent=(+boot).toLocaleString();$('#dealBoot').textContent=(+boot).toLocaleString();updatePot();screen('table');msg(`${name} joined. 5-seat table ready.`)}
function start(){if(state.roundActive)return;if(state.coins<state.boot){modal('Low balance','You do not have enough virtual chips for this room.');return}state.roundActive=true;state.seen=false;state.currentBet=state.boot;state.pot=0;state.deck=deck();state.myCards=[state.deck.pop(),state.deck.pop(),state.deck.pop()];state.bots.forEach(b=>b.cards=[state.deck.pop(),state.deck.pop(),state.deck.pop()]);resetBots();hideMine();$('#myStatus').textContent='BLIND';$('#dealBtn').classList.add('hidden');$('#actionBar').classList.remove('hidden');userPay(state.boot);state.bots.forEach(b=>botPay(b,state.boot));$('#roundLabel').textContent='Round live';msg(`Cards dealt • ${state.boot.toLocaleString()} boot from each player.`)}
function after(lbl){$('#myStatus').textContent=lbl;state.bots.forEach(botTurn);if(state.bots.filter(b=>!b.folded).length===0)return finish('user');if(state.pot>=state.boot*24||Math.random()<.1)finish('show')}
function seen(){if(!state.roundActive||state.seen)return;state.seen=true;showMine();state.currentBet=state.boot*2;updatePot();$('#myStatus').textContent='SEEN';msg(`${handName(state.myCards)} • Seen chaal is ${state.currentBet.toLocaleString()}.`)}
function chaal(){if(!state.roundActive)return;if(!userPay(state.currentBet)){modal('Low balance','Not enough virtual chips for this chaal.');return}msg(`You played chaal ${state.currentBet.toLocaleString()}.`);after('CHAAL')}
function revealBot(b){let e=$('#'+b.id).querySelector('.mini-cards');e.className='mini-cards revealed';e.textContent=b.cards.map(c=>c.r+c.s).join('  ')}
function finish(reason){if(!state.roundActive)return;state.roundActive=false;showMine();state.bots.filter(b=>!b.folded).forEach(revealBot);if(reason==='packed'){let a=state.bots.filter(b=>!b.folded),w=a[Math.floor(Math.random()*a.length)];w.coins+=state.pot;$('#'+w.id).querySelector('[data-coins]').textContent=w.coins.toLocaleString();msg(`You packed • ${w.name} wins ${state.pot.toLocaleString()} chips.`)}else if(reason==='user'){state.coins+=state.pot;save();msg(`Everyone packed • You win ${state.pot.toLocaleString()} chips!`)}else{let p=[{type:'user',name:'You',cards:state.myCards,folded:false},...state.bots.map(b=>({type:'bot',ref:b,name:b.name,cards:b.cards,folded:b.folded}))].filter(x=>!x.folded);p.sort((a,b)=>cmp(score(b.cards),score(a.cards)));let w=p[0];if(w.type==='user'){state.coins+=state.pot;save();msg(`SHOW • ${handName(state.myCards)} • You win ${state.pot.toLocaleString()} chips!`)}else{w.ref.coins+=state.pot;$('#'+w.ref.id).querySelector('[data-coins]').textContent=w.ref.coins.toLocaleString();msg(`SHOW • ${w.name} wins with ${handName(w.cards)} • Your hand: ${handName(state.myCards)}.`)}}state.pot=0;updatePot();$('#roundLabel').textContent='Round complete';$('#actionBar').classList.add('hidden');$('#dealBtn').classList.remove('hidden');$('#dealBtn span').textContent='DEAL AGAIN';state.round++;$('#roundNo').textContent=state.round}
function pack(){if(state.roundActive){$('#myStatus').textContent='PACK';finish('packed')}}function show(){if(!state.roundActive)return;let cost=state.currentBet*2;if(!userPay(cost)){modal('Low balance','Not enough virtual chips to request show.');return}finish('show')}
function modal(t,b){$('#modalTitle').textContent=t;$('#modalBody').textContent=b;$('#infoModal').classList.remove('hidden')}function closeModal(){$('#infoModal').classList.add('hidden')}
$('#playNowBtn').onclick=()=>enterRoom(100,'Rookie Club');$$('.room-card').forEach(x=>x.onclick=()=>enterRoom(x.dataset.boot,x.dataset.room));$('#dealBtn').onclick=start;$('#seenBtn').onclick=seen;$('#chaalBtn').onclick=chaal;$('#packBtn').onclick=pack;$('#showBtn').onclick=show;$('#backBtn').onclick=()=>state.roundActive?modal('Round in progress','Pack or finish the current round before leaving the table.'):screen('home');
$('#claimBonusBtn').onclick=()=>{if(state.bonusClaimed)return modal('Daily bonus','Today’s 5,000-chip bonus is already claimed. Come back tomorrow.');state.coins+=5000;state.bonusClaimed=true;localStorage.setItem('tpa_v2_bonus',today());save();$('#bonusText').textContent='CLAIMED TODAY';modal('Bonus collected','5,000 virtual chips were added to your wallet.')};
$('#privateBtn').onclick=()=>modal('Private Table','Private friend rooms are designed for the online multiplayer build.');$$('[data-coming]').forEach(x=>x.onclick=()=>modal(x.dataset.coming,x.dataset.coming+' mode will be added after Classic multiplayer is connected.'));$('#walletBtn').onclick=$('#navWallet').onclick=()=>modal('Virtual Wallet',`Balance: ${state.coins.toLocaleString()} chips. Virtual chips cannot be cashed out.`);$('#navProfile').onclick=()=>modal('Player Profile','Guest profile is active. Login, avatar, friends and leaderboard come with the online build.');$('#navTables').onclick=$('#navPlay').onclick=()=>enterRoom(100,'Rookie Club');$('#navHome').onclick=()=>screen('home');$('#soundBtn').onclick=()=>modal('Sound','Music and table sound effects will be connected in the polish pass.');$('#closeModal').onclick=$('#modalX').onclick=closeModal;
if(state.bonusClaimed)$('#bonusText').textContent='CLAIMED TODAY';updateMoney();updatePot();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
